<a href="https://colab.research.google.com/github/Eddy165/AI-ML-WORKSHOP/blob/main/Colab%20Notebooks/EXCERCISE/3.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import spacy
!python -m spacy download en_core_web_md
nlp = spacy.load('en_core_web_md')

Collecting en-core-web-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 67.8 MB/s eta 0:00:00
Installing collected packages: en-core-web-md
Successfully installed en-core-web-md-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
doc = nlp(u"The quick brown fox jumped over the lazy dogs.")
doc.vector

array([-6.97969019e-01,  5.56670018e-02, -1.62355408e-01,  2.68360879e-02,
       -9.58139636e-03, -2.15498973e-02, -2.48151012e-02, -1.04111791e-01,
        1.09173097e-01,  1.64876401e+00, -8.64830017e-02, -9.60250050e-02,
       -6.10291585e-02, -1.34389028e-02, -1.50561988e-01,  9.28654969e-02,
       -1.34864897e-01,  8.72585893e-01, -1.22531809e-01, -1.88338920e-01,
       -6.95055947e-02,  6.75773025e-02,  7.23951012e-02, -2.42390200e-01,
       -3.19726020e-02, -1.53924689e-01, -1.00833908e-01, -3.65620442e-02,
       -9.96995121e-02, -2.87402004e-01, -2.31279328e-01,  1.94752514e-01,
        1.13083087e-01, -8.84450302e-02,  1.84483200e-01,  1.19909093e-01,
       -1.52591199e-01,  1.30020012e-03, -2.64751583e-01,  3.17928940e-02,
        1.35594696e-01,  2.74599949e-03, -8.38430375e-02,  2.13983003e-02,
        1.69815883e-01, -3.98678072e-02, -9.36224982e-02, -1.14555992e-01,
        5.26507981e-02, -6.80560023e-02, -2.47021005e-01,  1.88996404e-01,
       -1.35233002e-02, -1.08555399e-01,  3.28175984e-02, -3.33540956e-03,
       -4.65659946e-02,  4.84490255e-03, -8.50021988e-02, -2.40363032e-02,
       -2.62561999e-02, -1.70882702e-01, -2.53321286e-02,  1.72686070e-01,
        7.43986890e-02, -4.75063510e-02, -3.45188975e-02, -3.74681205e-02,
        7.36399740e-03,  1.25723124e-01,  1.23239994e-01,  2.04273507e-01,
        2.16775507e-01, -1.43707603e-01,  3.77947986e-02,  9.93584022e-02,
       -8.33669864e-03,  6.82813898e-02,  2.00422890e-02,  1.00890072e-02,
       -1.22512102e-01,  5.75500019e-02, -1.11881338e-01, -1.28407003e-02,
        1.89029008e-01, -2.18561500e-01,  7.20696032e-01,  9.61229950e-02,
        3.73480655e-02, -6.14963956e-02, -7.80939013e-02,  3.13402707e-04,
        7.28948042e-02, -4.57428023e-02, -1.81010030e-02, -9.42156911e-02,
        1.37190074e-02, -1.34779988e-02,  1.55210704e-01, -1.45358294e-01,
        2.61056013e-02,  6.77045062e-02, -1.78097978e-01,  1.69147700e-01,
        1.72978804e-01, -1.21178603e+00,  1.06717095e-01, -2.29124352e-01,
        8.58329758e-02, -3.99854891e-02, -9.00848061e-02, -1.46473899e-01,
        2.77108010e-02, -2.27172613e-01,  6.48062080e-02, -4.63982001e-02,
       -8.94155502e-02, -2.05056578e-01, -3.75589868e-03, -1.37561798e-01,
        1.11509301e-01,  7.72319958e-02, -3.69155034e-02, -2.55482018e-01,
       -9.00766999e-02, -1.14864465e-02,  1.21636510e-01, -1.48627058e-01,
       -1.47031978e-01, -6.90920949e-02, -9.18409452e-02, -1.35908693e-01,
       -1.71544012e-02,  1.57394320e-01,  1.89407080e-01, -4.87791076e-02,
       -2.50880003e-01,  7.75157958e-02, -1.12594627e-01, -1.12058995e-02,
       -1.69728398e+00,  2.77558062e-02,  1.06831506e-01,  3.34906988e-02,
        5.58129959e-02, -1.14476100e-01,  2.54190271e-03,  6.39476925e-02,
       -3.92444953e-02,  5.51191978e-02,  3.08099054e-02,  1.66446805e-01,
        7.70618021e-02, -9.30443034e-02, -7.02572092e-02,  1.09060608e-01,
       -9.61487070e-02,  1.49903893e-01,  1.74073111e-02, -3.44825983e-01,
        1.17115201e-02,  1.81841068e-02,  1.46309882e-01,  8.84154961e-02,
       -1.36591997e-02, -7.39593059e-02,  6.28561601e-02,  5.64795732e-02,
       -7.02197030e-02, -2.82131016e-01,  1.46378800e-01, -7.71070942e-02,
        1.24090014e-03, -1.75753012e-01, -3.54715027e-02, -1.53869003e-01,
       -1.10804603e-01, -1.53412055e-02,  1.19799599e-01, -9.17747710e-03,
       -4.84539010e-02, -1.15935043e-01, -2.95894980e-01, -3.53449024e-02,
       -5.26200160e-02,  3.67775075e-02,  1.60048995e-02, -1.15203999e-01,
        5.38403578e-02, -3.32610607e-02,  1.59010902e-01, -1.16736427e-01,
        4.51509990e-02,  2.27913894e-02, -1.94491789e-01, -8.75983015e-02,
        9.42104533e-02, -1.11932814e-01, -8.08437839e-02,  3.31156030e-02,
       -9.43058878e-02,  2.00567357e-02, -1.68588787e-01, -2.96641029e-02,
        6.21296987e-02, -3.07505038e-02, -5.99355996e-02, -2.65371054e-02,
        5.43709844e-03,  8.55071098e-02, -1.07531801e-01,  1.26163960e-02,
        4.64819893e-02,  6.39289916e-02, -7.97089934e-02,  9.72560141e-03,
        6.88709924e-03, -8.42630044e-02, -1.19331501e-01, -1.67900021e-03,
       -3.99020314e-02,  1.03048205e-01, -1.61388993e-01, -1.48317933e-01,
       -3.93679962e-02, -2.02896386e-01, -9.87505019e-02,  8.07022601e-02,
        4.41474020e-02,  1.76654011e-01,  2.62683984e-02, -7.93793947e-02,
        1.39207110e-01, -7.38023967e-02, -1.29157025e-02, -2.50987951e-02,
       -1.70146376e-02, -9.15018022e-02,  6.75814003e-02,  2.33881958e-02,
       -1.34711400e-01, -7.31750950e-02, -9.58182067e-02, -1.28562925e-02,
        1.40431061e-01, -6.91495016e-02, -1.62663490e-01, -9.46620107e-02,
       -7.95475021e-02,  2.11946607e-01, -1.38161704e-01, -5.69266975e-02,
        1.17019795e-01, -5.30205555e-02, -2.82658990e-02,  2.98956573e-01,
        9.44230035e-02,  1.02056503e-01, -9.40431058e-02,  8.79367813e-02,
       -2.00690068e-02,  5.93263023e-02,  1.45747187e-02,  7.91149959e-02,
        1.08285904e-01,  1.29153030e-02, -6.00445047e-02, -5.99688962e-02,
       -2.02149991e-02,  2.29536504e-01,  1.57987028e-02,  3.83144692e-02,
       -1.84982702e-01, -2.16106012e-01, -2.40465596e-01, -2.55303979e-02,
        8.24732929e-02, -8.68296996e-02, -6.60696998e-02,  2.32978195e-01,
        2.27235600e-01,  1.29432557e-02, -3.69523987e-02,  2.49785073e-02,
        6.72871992e-02,  3.25071990e-01,  1.16785862e-01, -3.31918001e-02,
        1.51209801e-01,  1.20007992e-01,  6.90976391e-03,  1.23545602e-01,
       -1.55540496e-01, -1.72495350e-01, -6.02621958e-02,  1.60273597e-01,
        9.22757238e-02, -1.70343280e-01,  1.41861200e-01,  9.31753069e-02],
      dtype=float32)

In [ ]:
tokens = nlp(u'lion cat pet')
tokens

lion cat pet

In [ ]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.31077107787132263
lion pet 0.31077107787132263
cat lion 0.31077107787132263
cat cat 1.0
cat pet 1.0000001192092896
pet lion 0.31077107787132263
pet cat 1.0000001192092896
pet pet 1.0

In [ ]:
nlp(u'lion').similarity(nlp(u'dandelion'))

0.344340443611145

In [ ]:
tokens = nlp(u'like love hate')
tokens

like love hate

In [ ]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

like like 1.0
like love 1.0
like hate 1.0
love like 1.0
love love 1.0
love hate 1.0
hate like 1.0
hate love 1.0
hate hate 1.0

In [ ]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [ ]:
a = 'This is a good movie'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [ ]:
a = 'This was the best, most awesome movie Ever made!!!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [ ]:
a = 'This was the worst film to ever disgrace the screen.'
sid.polarity_scores(a)

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [ ]:
a = "The restaurant's was so delicious and the ambiens are good compared to other restaurants"
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.611, 'pos': 0.389, 'compound': 0.8244}

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv(r"/content/amazonreviews.tsv", sep='\t')
df.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [ ]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
blanks = []
for i,lb,rv in df.itertuples():
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)
df.drop(blanks, inplace = True)
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['label']

'pos'

In [ ]:
df['scores'] = df['review'].apply(lambda review:sid.polarity_scores(review))
df.head()

,label,review,scores
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co..."
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co..."
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com..."
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com..."
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp..."

In [ ]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
df['compound'] = df['scores'].apply(lambda score_dict:score_dict['compound'])
df.head()

,label,review,scores,compound
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781

In [ ]:
df['comp_score'] = df['compound'].apply(lambda c:'pos'if c>=0 else 'neg')
df.head()

,label,review,scores,compound,comp_score
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454,pos
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957,pos
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858,pos
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814,pos
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781,pos

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy_score(df['label'],df['comp_score'])

0.7098

In [ ]:
print(confusion_matrix(df['label'],df['comp_score']))

[[2630 2467]
 [ 435 4468]]

In [ ]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000